"""occasions categories tags measurements, drop price

Revision ID: a13414dc63bd
Revises: 6df3f2ad1b51
Create Date: 2026-07-11 04:25:36.175905
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a13414dc63bd'
down_revision: Union[str, None] = '6df3f2ad1b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('looks', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('looks', sa.Column('occasions', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('looks', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_looks_category'), 'looks', ['category'], unique=False)
    op.drop_column('looks', 'price')
    op.add_column('users', sa.Column('measurements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'measurements')
    op.add_column('looks', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_looks_category'), table_name='looks')
    op.drop_column('looks', 'tags')
    op.drop_column('looks', 'occasions')
    op.drop_column('looks', 'category')
    # ### end Alembic commands ###
