"""moodboards

Revision ID: 6df3f2ad1b51
Revises: 52ff853972f9
Create Date: 2026-07-11 03:03:52.770369
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6df3f2ad1b51'
down_revision: Union[str, None] = '52ff853972f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodboards',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodboards_id'), 'moodboards', ['id'], unique=False)
    op.create_index(op.f('ix_moodboards_user_id'), 'moodboards', ['user_id'], unique=False)
    op.create_table('moodboard_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('moodboard_id', sa.Uuid(), nullable=False),
    sa.Column('look_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['look_id'], ['looks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moodboard_id'], ['moodboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moodboard_id', 'look_id', name='uq_moodboard_look')
    )
    op.create_index(op.f('ix_moodboard_items_id'), 'moodboard_items', ['id'], unique=False)
    op.create_index(op.f('ix_moodboard_items_look_id'), 'moodboard_items', ['look_id'], unique=False)
    op.create_index(op.f('ix_moodboard_items_moodboard_id'), 'moodboard_items', ['moodboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moodboard_items_moodboard_id'), table_name='moodboard_items')
    op.drop_index(op.f('ix_moodboard_items_look_id'), table_name='moodboard_items')
    op.drop_index(op.f('ix_moodboard_items_id'), table_name='moodboard_items')
    op.drop_table('moodboard_items')
    op.drop_index(op.f('ix_moodboards_user_id'), table_name='moodboards')
    op.drop_index(op.f('ix_moodboards_id'), table_name='moodboards')
    op.drop_table('moodboards')
    # ### end Alembic commands ###
